[package]
name = "contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ws-sdk =  { path = "../.." }
anyhow = "1.0.69"
ethabi ={ version =  "17.2.0", default-features = false, features = ["full-serde"] }
lazy_static = "1.4.0"
serde_json = "1.0"
hex = "0.4.3"